// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5IZXjo1d8fM_Ha74463nHtIIhJgYf5Hk',
    appId: '1:333668792885:web:46634b61d4469178d28f7c',
    messagingSenderId: '333668792885',
    projectId: 'shloka-recitation-project',
    authDomain: 'shloka-recitation-project.firebaseapp.com',
    storageBucket: 'shloka-recitation-project.firebasestorage.app',
    measurementId: 'G-SFBRRSYPZX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9uoBqbfOdt7WxJTgtWLhWTh4pnjLZ7h8',
    appId: '1:333668792885:android:bcca8e4340ec1da1d28f7c',
    messagingSenderId: '333668792885',
    projectId: 'shloka-recitation-project',
    storageBucket: 'shloka-recitation-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIfoY97S60_OB0C9B1fc9TXY_d6EMrCwQ',
    appId: '1:333668792885:ios:9cc6674958962e15d28f7c',
    messagingSenderId: '333668792885',
    projectId: 'shloka-recitation-project',
    storageBucket: 'shloka-recitation-project.firebasestorage.app',
    iosBundleId: 'com.example.sanskritRacitatiionProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIfoY97S60_OB0C9B1fc9TXY_d6EMrCwQ',
    appId: '1:333668792885:ios:9cc6674958962e15d28f7c',
    messagingSenderId: '333668792885',
    projectId: 'shloka-recitation-project',
    storageBucket: 'shloka-recitation-project.firebasestorage.app',
    iosBundleId: 'com.example.sanskritRacitatiionProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5IZXjo1d8fM_Ha74463nHtIIhJgYf5Hk',
    appId: '1:333668792885:web:1e75aff424a7f5dad28f7c',
    messagingSenderId: '333668792885',
    projectId: 'shloka-recitation-project',
    authDomain: 'shloka-recitation-project.firebaseapp.com',
    storageBucket: 'shloka-recitation-project.firebasestorage.app',
    measurementId: 'G-VGJTFQPN9B',
  );
}
